import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const montserrat = Montserrat({
  subsets: ['vietnamese'],
  weight: ['400', '700'], 
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

console.log = () => {};
console.info = () => {};
console.warn = () => {};
console.error=()=>{};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}`}
      >
        <section className="w-screen h-fit min-h-screen relative bg-gray-950">
          <Nav />
          {children}
        </section>
        
      </body>
    </html>
  );
}
